export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const CHECKOUT = "CHECKOUT";
export const SET_ERRORS = "SET_ERRORS";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_DETAIL = "PROFILE_DETAIL";