
export const FITCH_CART_LIST = "FITCH_CART_LIST";
export const ADD_ITEM_CART = "ADD_ITEM_CART";
export const UPDATE_ITEM_CART = "UPDATE_ITEM_CART";
export const DELETE_ITEM_CART = "DELETE_ITEM_CART";
export const CHECKOUT = "CHECKOUT";
export const SET_ERRORS = "SET_ERRORS";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PROFILE_DETAIL = "PROFILE_DETAIL";